Exercise toast in tests
The test should basically run on all major versions (modulo lz4
support), but on versions before 14, it fails with missing toast chunks:

ERROR:  XX001: unexpected chunk number 4 (expected 0) for toast value 16392 in pg_toast_16384

Using pg_dirtyread directly on the toast table confirms the rows are
missing (but not all).